DROP TABLE IF EXISTS FLIGHT_SCHEDULE_DETAILS;

CREATE TABLE FLIGHT_SCHEDULE_DETAILS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  FLIGHT_NUMBER VARCHAR(250) NOT NULL,
  DEPARTURE_AIRPORT VARCHAR(250) NOT NULL,
  ARRIVAL_AIRPORT VARCHAR(250) NOT NULL,
  DEPARTURE_TIME TIME NOT NULL,
  ARRIVAL_TIME TIME NOT NULL
);

INSERT INTO FLIGHT_SCHEDULE_DETAILS (FLIGHT_NUMBER,DEPARTURE_AIRPORT, ARRIVAL_AIRPORT, DEPARTURE_TIME,ARRIVAL_TIME) VALUES
('501', 'BOM', 'DXB',PARSEDATETIME('4:30', 'hh:mm'),PARSEDATETIME('6:00', 'hh:mm')),
('2137', 'BOM', 'DXB',PARSEDATETIME('5:10', 'HH:mm'),PARSEDATETIME('6:50', 'HH:mm')),
('507', 'BOM', 'DXB',PARSEDATETIME('15:35', 'HH:mm'),PARSEDATETIME('20:00', 'HH:mm')),
('503', 'BOM', 'DXB',PARSEDATETIME('19:20', 'HH:mm'),PARSEDATETIME('19:20', 'HH:mm')),
('201', 'DXB', 'JFK',PARSEDATETIME('8:30', 'HH:mm'),PARSEDATETIME('14:25', 'HH:mm')),
('203', 'DXB', 'JFK',PARSEDATETIME('2:50', 'HH:mm'),PARSEDATETIME('8:50', 'HH:mm')),
('205', 'DXB', 'JFK',PARSEDATETIME('9:45', 'HH:mm'),PARSEDATETIME('19:00', 'HH:mm')),
('211', 'DXB', 'IAH',PARSEDATETIME('9:35', 'HH:mm'),PARSEDATETIME('16:50', 'HH:mm'));

