DROP TABLE IF EXISTS AIRPORT;

CREATE TABLE AIRPORT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  AIRPORT_CODE VARCHAR(250) NOT NULL,
  AIRPORT_NAME VARCHAR(250) NOT NULL,
  CITY_NAME VARCHAR(250) NOT NULL,
  COORDINATES VARCHAR(250) DEFAULT NULL
);

INSERT INTO AIRPORT (AIRPORT_CODE,AIRPORT_NAME, CITY_NAME, COORDINATES) VALUES
('BOM', 'Chhatrapati Shivaji Maharaj International Airport', 'Mumbai','19°04′19″N 72°52′05″E'),
('DXB', 'Dubai Internation Airport', 'Dubai','25°15′10″N 55°21′52″E'),
('JFK', 'John F. Kennedy International Airport', 'New York','40°38′23″N 73°46′44″W'),
('IAH', 'George Bush Intercontinental Airport', 'Houston','29°59′04″N 95°20′29″W');

